### ISSUE TITLE
Bootstrap AdEx interface app

### ISSUE THREAD

**Issue by IvoPaunov** [AmbireTech/adex-interface#1]
## Summary

Crate AdEx interface base architecture with react - hooks, context and providers. Research use of styled components and libs for date/time pickers, charts and maps

The lates design can be found [here](https://xd.adobe.com/view/8c6fd79e-8d7b-4ae7-a615-0f00d128a6f3-d93c/)

### Tasks

- [x] #2
- [x]  Basic app architecture
- [x]  Research and integrate framework for styled components if needed. We can go with styled components only.
- [x]  Research and integrate react components for date/time pickers
<s>- [ ]  Research and integrate react components charts</s>
<s>- [ ]  Research and integrate react components maps</s>
- [x]  Setup eslint and push hooks
